### PR TITLE
[Feature] finish the majority part of discussion board

### PR DESCRIPTION
**Pull request by chloeg12**
image
image
image
image

### CODE REVIEW

**Review by rebeccali04 — APPROVED** [review]
Amazing job!

**Review by rebeccali04 — COMMENTED** [review]
Hey Chloe, 
One thing I noticed is that it’s actually the analyze component that invokes the threads component, whereas the discussion component simply changes the state the global variables. Is my understanding correct? 
I was wondering if perhaps you could document where the new code is located/ what each file now functions to do somewhere so others can see their relationships between the component since I think it’s non-obvious by their names.

**Comment by chloeg12** [comment]
image
image

**Comment by chloeg12** [comment]
image

**Comment by chloeg12** [comment]
image

**Comment by chloeg12** [comment]
image

**Comment by chloeg12** [comment]
image

**Review by rebeccali04 — APPROVED** [review]
LGTM

**Review by oreliapi — APPROVED** [review]
LGTM!

**Pull request merged**
